import { useState } from 'react';
import { Alert, StyleSheet, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { createCheckInInputSchema, type CreateCheckInInput, type MoodValue, type SleepQuality } from '@bemmecuida/domain';
import { useAuth } from '@/auth/AuthProvider';
import { AppText } from '@/components/AppText';
import { MoodSelector } from '@/components/MoodSelector';
import { PrimaryButton } from '@/components/PrimaryButton';
import { ScaleInput } from '@/components/ScaleInput';
import { Screen } from '@/components/Screen';
import { Surface } from '@/components/Surface';
import { saveCheckIn } from '@/data/check-in-repository';
import { useSync } from '@/sync/SyncProvider';
import { colors, radius, spacing } from '@/theme/tokens';
const initialState: CreateCheckInInput = { mood: 'neutral', anxiety: 4, energy: 4, irritability: 2, agitation: 2, impulsivity: 2, concentration: 4, craving: 0, sleepQuality: 'partial', sleepMinutes: null, note: null };
export default function CheckInScreen() {
  const { session } = useAuth(); const { syncNow } = useSync(); const [form, setForm] = useState<CreateCheckInInput>(initialState); const [saving, setSaving] = useState(false);
  function update<K extends keyof CreateCheckInInput>(key: K, value: CreateCheckInInput[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function handleSave() { const parsed = createCheckInInputSchema.safeParse(form); if (!parsed.success) { Alert.alert('Revise o registro', 'Há um campo fora do intervalo permitido.'); return; } setSaving(true); try { if (!session) throw new Error('missing_session'); await saveCheckIn(parsed.data, session.user.id); void syncNow(); Alert.alert('Check-in salvo', 'Seu registro foi guardado neste aparelho.', [{ text: 'Ver meu dia', onPress: () => router.replace('/(tabs)') }]); setForm(initialState); } catch { Alert.alert('Não foi possível salvar', 'Tente novamente. Nenhuma informação foi enviada.'); } finally { setSaving(false); } }
  return <Screen><AppText variant="caption" muted>CHECK-IN RÁPIDO</AppText><AppText variant="h1" testID="check-in-title" style={styles.title}>Como você está agora?</AppText><AppText muted style={styles.description}>Não existe resposta certa. Registre apenas o que consegue perceber neste momento.</AppText>
    <Surface style={styles.section}><AppText variant="h2">Humor</AppText><MoodSelector value={form.mood as MoodValue} onChange={(value) => update('mood', value)} testIDPrefix="check-in-mood" /></Surface>
    <Surface style={styles.section}><ScaleInput label="Ansiedade" value={form.anxiety} onChange={(value) => update('anxiety', value)} testIDPrefix="check-in-anxiety" /><ScaleInput label="Energia" value={form.energy} onChange={(value) => update('energy', value)} testIDPrefix="check-in-energy" /><ScaleInput label="Irritabilidade" value={form.irritability} onChange={(value) => update('irritability', value)} testIDPrefix="check-in-irritability" /><ScaleInput label="Agitação" value={form.agitation} onChange={(value) => update('agitation', value)} testIDPrefix="check-in-agitation" /><ScaleInput label="Impulsividade" value={form.impulsivity} onChange={(value) => update('impulsivity', value)} testIDPrefix="check-in-impulsivity" /><ScaleInput label="Concentração" value={form.concentration} onChange={(value) => update('concentration', value)} lowLabel="Difícil" highLabel="Boa" testIDPrefix="check-in-concentration" /><ScaleInput label="Vontade de usar substância" value={form.craving} onChange={(value) => update('craving', value)} lowLabel="Nenhuma" highLabel="Muito forte" testIDPrefix="check-in-craving" /></Surface>
    <Surface style={styles.section}><AppText variant="h2">Sono</AppText><View style={styles.sleepRow}>{([['poor','Ruim'],['partial','Parcial'],['good','Bom']] as Array<[SleepQuality,string]>).map(([value,label]) => <AppText key={value} accessibilityRole="button" onPress={() => update('sleepQuality', value)} style={[styles.sleepOption, form.sleepQuality === value && styles.sleepSelected]}>{label}</AppText>)}</View></Surface>
    <Surface style={styles.section}><AppText variant="h2">Algo importante para registrar?</AppText><TextInput accessibilityLabel="Nota opcional do check-in" value={form.note ?? ''} onChangeText={(value) => update('note', value.trim().length ? value : null)} placeholder="Uma frase já é suficiente." placeholderTextColor={colors.textMuted} multiline maxLength={500} testID="check-in-note" style={styles.input} /><AppText variant="caption" muted>{form.note?.length ?? 0}/500</AppText></Surface>
    <PrimaryButton testID="check-in-save" label="Salvar check-in" onPress={handleSave} loading={saving} /><AppText variant="caption" muted style={styles.privacy}>Salvo primeiro neste aparelho. A sincronização ocorre somente quando houver configuração e sessão válidas.</AppText></Screen>;
}
const styles = StyleSheet.create({ title: { marginTop: spacing.xs }, description: { marginTop: spacing.sm, marginBottom: spacing.xl }, section: { gap: spacing.lg, marginBottom: spacing.md }, sleepRow: { flexDirection: 'row', gap: spacing.sm }, sleepOption: { flex: 1, textAlign: 'center', paddingVertical: spacing.md, borderRadius: radius.sm, backgroundColor: colors.surfaceMuted, overflow: 'hidden' }, sleepSelected: { color: colors.white, backgroundColor: colors.primaryStrong }, input: { minHeight: 120, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, color: colors.text, textAlignVertical: 'top', fontSize: 16 }, privacy: { textAlign: 'center', marginTop: spacing.md, marginBottom: spacing.xl } });
