import { Link, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';

import { useAuth } from '@/auth/AuthProvider';
import { AppText } from '@/components/AppText';
import { BackHeader } from '@/components/BackHeader';
import { ChoiceChip } from '@/components/ChoiceChip';
import { Screen } from '@/components/Screen';
import { Surface } from '@/components/Surface';
import { listActivityPage, type ActivityFilterKind, type RecentActivity } from '@/data/recent-activity-repository';
import { colors, radius, spacing } from '@/theme/tokens';

type Period = 7 | 30 | 90 | 'all';
const PAGE_SIZE = 20;
const kindLabel: Record<RecentActivity['kind'], string> = { medication: 'MEDICAÇÃO', practice: 'PRÁTICA', check_in: 'CHECK-IN' };
const kindIcon: Record<RecentActivity['kind'], string> = { medication: '💊', practice: '🌿', check_in: '😊' };
function formatDate(value:string){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}
function sinceFor(period:Period):string|null{return period==='all'?null:new Date(Date.now()-period*86_400_000).toISOString();}
export default function CareHistoryScreen(){
 const {session}=useAuth(); const[items,setItems]=useState<RecentActivity[]>([]); const[kind,setKind]=useState<ActivityFilterKind>('all'); const[period,setPeriod]=useState<Period>(30); const[query,setQuery]=useState(''); const[loading,setLoading]=useState(true); const[loadingMore,setLoadingMore]=useState(false); const[hasMore,setHasMore]=useState(false); const[error,setError]=useState(false);
 const load=useCallback(async(append=false)=>{if(!session)return;append?setLoadingMore(true):setLoading(true);setError(false);try{const page=await listActivityPage(session.user.id,{limit:PAGE_SIZE,offset:append?items.length:0,kind,query,since:sinceFor(period)});setItems(current=>append?[...current,...page.items]:page.items);setHasMore(page.hasMore);}catch{setError(true);if(!append)setItems([]);}finally{setLoading(false);setLoadingMore(false);}},[items.length,kind,period,query,session]);
 useFocusEffect(useCallback(()=>{void load(false);},[kind,period,session]));
 const groups=useMemo(()=>{const result=new Map<string,RecentActivity[]>();for(const item of items){const key=new Intl.DateTimeFormat('pt-BR',{dateStyle:'long'}).format(new Date(item.occurredAt));result.set(key,[...(result.get(key)??[]),item]);}return[...result.entries()];},[items]);
 const submitSearch=useCallback(()=>{void load(false);},[load]);
 return <Screen><BackHeader eyebrow="HISTÓRICO DE CUIDADO" title="Seus registros, no seu ritmo"/><Surface style={styles.filters} testID="history-filters"><AppText variant="bodyStrong">Buscar</AppText><View style={styles.searchRow}><TextInput testID="history-search-input" accessibilityLabel="Buscar no histórico" value={query} onChangeText={setQuery} onSubmitEditing={submitSearch} placeholder="Medicamento, prática ou check-in" placeholderTextColor={colors.textMuted} returnKeyType="search" style={styles.searchInput}/><Pressable testID="history-search-submit" accessibilityRole="button" onPress={submitSearch} style={styles.searchButton}><AppText variant="bodyStrong" style={styles.searchButtonText}>Buscar</AppText></Pressable></View><AppText variant="bodyStrong">Tipo</AppText><View style={styles.chips}><ChoiceChip label="Tudo" selected={kind==='all'} onPress={()=>setKind('all')}/><ChoiceChip label="Medicamentos" selected={kind==='medication'} onPress={()=>setKind('medication')}/><ChoiceChip label="Práticas" selected={kind==='practice'} onPress={()=>setKind('practice')}/><ChoiceChip label="Check-ins" selected={kind==='check_in'} onPress={()=>setKind('check_in')}/></View><AppText variant="bodyStrong">Período</AppText><View style={styles.chips}>{([7,30,90] as const).map(value=><ChoiceChip key={value} label={`${value} dias`} selected={period===value} onPress={()=>setPeriod(value)}/>)}<ChoiceChip label="Tudo" selected={period==='all'} onPress={()=>setPeriod('all')}/></View></Surface>
 {loading?<Surface testID="history-loading"><AppText muted>Carregando seus registros…</AppText></Surface>:error?<Surface style={styles.errorCard} testID="history-error"><AppText variant="bodyStrong">Não foi possível carregar o histórico.</AppText><AppText variant="caption" muted>Seus registros continuam salvos no aplicativo.</AppText><Pressable accessibilityRole="button" onPress={()=>void load(false)} style={styles.retryButton}><AppText variant="bodyStrong" style={styles.retryText}>Tentar novamente</AppText></Pressable></Surface>:groups.length?groups.map(([date,dateItems])=><View key={date} style={styles.group}><AppText variant="h2" style={styles.date}>{date}</AppText><Surface style={styles.list}>{dateItems.map((item,index)=><Link key={`${item.kind}-${item.id}`} href={item.href} asChild><Pressable accessibilityRole="button" accessibilityLabel={`${item.title}, ${item.detail}, ${formatDate(item.occurredAt)}, ${item.synced?'sincronizado':'aguardando sincronização'}`} style={[styles.row,index>0&&styles.divider]}><View style={styles.icon}><AppText>{kindIcon[item.kind]}</AppText></View><View style={styles.flex}><AppText variant="caption" style={styles.kind}>{kindLabel[item.kind]}</AppText><AppText variant="bodyStrong">{item.title}</AppText><AppText variant="caption" muted>{item.detail} · {formatDate(item.occurredAt)}</AppText></View><View style={[styles.badge,item.synced?styles.synced:styles.pending]}><AppText variant="caption" style={item.synced?styles.syncedText:styles.pendingText}>{item.synced?'Sincronizado':'Pendente'}</AppText></View></Pressable></Link>)}</Surface></View>):<Surface testID="history-empty"><AppText muted>Nenhum registro corresponde aos filtros escolhidos.</AppText></Surface>}
 {hasMore&&!loading?<Pressable testID="history-load-more" accessibilityRole="button" disabled={loadingMore} onPress={()=>void load(true)} style={[styles.loadMore,loadingMore&&styles.disabled]}><AppText variant="bodyStrong" style={styles.loadMoreText}>{loadingMore?'Carregando…':'Carregar mais'}</AppText></Pressable>:null}<AppText variant="caption" muted style={styles.footer}>Este histórico descreve registros feitos por você. Ele não avalia eficácia ou segurança do tratamento.</AppText></Screen>;
}
const styles=StyleSheet.create({filters:{gap:spacing.md,marginBottom:spacing.xl},searchRow:{flexDirection:'row',gap:spacing.sm},searchInput:{flex:1,minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,color:colors.text,backgroundColor:colors.surface},searchButton:{justifyContent:'center',backgroundColor:colors.primaryStrong,borderRadius:radius.md,paddingHorizontal:spacing.lg},searchButtonText:{color:colors.white},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},group:{marginBottom:spacing.xl},date:{marginBottom:spacing.md,textTransform:'capitalize'},list:{paddingVertical:spacing.sm},row:{minHeight:64,flexDirection:'row',alignItems:'center',gap:spacing.md,paddingVertical:spacing.md},divider:{borderTopWidth:1,borderTopColor:colors.border},icon:{width:40,height:40,borderRadius:radius.pill,backgroundColor:colors.surfaceMuted,alignItems:'center',justifyContent:'center'},flex:{flex:1,gap:spacing.xs},kind:{color:colors.primaryStrong,fontWeight:'700'},badge:{borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},synced:{backgroundColor:colors.primarySoft},pending:{backgroundColor:colors.sand},syncedText:{color:colors.primaryStrong},pendingText:{color:colors.textMuted},errorCard:{gap:spacing.sm,backgroundColor:colors.dangerSoft},retryButton:{alignSelf:'flex-start',backgroundColor:colors.primaryStrong,borderRadius:radius.md,paddingHorizontal:spacing.lg,paddingVertical:spacing.sm},retryText:{color:colors.white},loadMore:{alignItems:'center',backgroundColor:colors.primaryStrong,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.xl},loadMoreText:{color:colors.white},disabled:{opacity:.55},footer:{textAlign:'center',marginBottom:spacing.xl}});
