import { Link, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { AppText } from '@/components/AppText';
import { Surface } from '@/components/Surface';
import { getWeeklyActivityFacts, listWeeklyDailyFacts, type DailyActivityFacts, type WeeklyActivityFacts } from '@/data/recent-activity-repository';
import { colors, radius, spacing } from '@/theme/tokens';
const emptyFacts: WeeklyActivityFacts = { medicationRecords: 0, practiceRecords: 0, checkInRecords: 0, activeDays: 0, checkInDays: 0, totalRecords: 0 };
function sevenDayStart(): Date { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6); }
function localDateKey(date: Date): string { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function buildSevenDays(rows: DailyActivityFacts[]): DailyActivityFacts[] { const byDate = new Map(rows.map((row) => [row.date, row])); const start = sevenDayStart(); return Array.from({ length: 7 }, (_, index) => { const date = new Date(start.getFullYear(), start.getMonth(), start.getDate() + index); const key = localDateKey(date); return byDate.get(key) ?? { date: key, medicationRecords: 0, practiceRecords: 0, checkInRecords: 0, totalRecords: 0 }; }); }
function dateFromKey(key: string): Date { const parts = key.split('-'); if (parts.length !== 3) return new Date(key); return new Date(Number(parts[0] ?? 0), Number(parts[1] ?? 1) - 1, Number(parts[2] ?? 1)); }
function dayLabel(key: string): string { return new Intl.DateTimeFormat('pt-BR', { weekday: 'short' }).format(dateFromKey(key)).replace('.', ''); }
export function WeeklyFactualSummary({ refreshToken }: { refreshToken: string }) {
  const { session } = useAuth(); const [facts, setFacts] = useState<WeeklyActivityFacts>(emptyFacts); const [days, setDays] = useState<DailyActivityFacts[]>([]); const [failed, setFailed] = useState(false);
  const load = useCallback(async () => { if (!session) return; try { const since = sevenDayStart().toISOString(); const [weekly, daily] = await Promise.all([getWeeklyActivityFacts(session.user.id, since), listWeeklyDailyFacts(session.user.id, since)]); setFacts(weekly); setDays(buildSevenDays(daily)); setFailed(false); } catch { setFailed(true); } }, [refreshToken, session]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  return <><View style={styles.headingRow}><View><AppText variant="h2">Últimos 7 dias</AppText><AppText variant="caption" muted>Hoje e os seis dias anteriores</AppText></View><Link href="/weekly-report" asChild><Pressable testID="home-open-weekly-report" accessibilityRole="button"><AppText variant="caption" style={styles.linkText}>Ver relatório</AppText></Pressable></Link></View><Surface testID="home-weekly-factual-summary" style={styles.card}>{failed ? <View style={styles.emptyState}><AppText variant="bodyStrong">Não foi possível atualizar a semana agora.</AppText><AppText variant="caption" muted>Os registros continuam salvos no aplicativo.</AppText></View> : facts.totalRecords > 0 ? <><View style={styles.grid}><View style={styles.metric}><AppText variant="display">{facts.medicationRecords}</AppText><AppText variant="caption" muted>medicações registradas</AppText></View><View style={styles.metric}><AppText variant="display">{facts.practiceRecords}</AppText><AppText variant="caption" muted>práticas registradas</AppText></View><View style={styles.metric}><AppText variant="display">{facts.checkInDays}/7</AppText><AppText variant="caption" muted>dias com check-in</AppText></View><View style={styles.metric}><AppText variant="display">{facts.activeDays}/7</AppText><AppText variant="caption" muted>dias com algum registro</AppText></View></View><View testID="home-weekly-daily-breakdown" style={styles.daysRow}>{days.map((item) => <View key={item.date} accessibilityLabel={`${dayLabel(item.date)}, ${item.totalRecords} registros`} style={styles.dayItem}><AppText variant="caption" muted>{dayLabel(item.date)}</AppText><AppText variant="bodyStrong">{item.totalRecords}</AppText><View style={styles.kindRow}>{item.medicationRecords > 0 ? <AppText variant="caption">💊</AppText> : null}{item.practiceRecords > 0 ? <AppText variant="caption">🌿</AppText> : null}{item.checkInRecords > 0 ? <AppText variant="caption">😊</AppText> : null}{item.totalRecords === 0 ? <AppText variant="caption" muted>—</AppText> : null}</View></View>)}</View><View style={styles.noteBox}><AppText variant="caption" muted>{facts.totalRecords} registro(s) no período. Cada coluna mostra o total factual do dia e as categorias presentes.</AppText></View></> : <View style={styles.emptyState}><AppText variant="bodyStrong">Nenhum registro nos últimos 7 dias.</AppText><AppText variant="caption" muted>Tomadas, práticas e check-ins aparecerão aqui quando forem registrados.</AppText></View>}</Surface></>;
}
const styles = StyleSheet.create({ headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md, marginTop: spacing.xl, marginBottom: spacing.md }, linkText: { color: colors.primaryStrong, fontWeight: '700' }, card: { gap: spacing.md }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, metric: { width: '47%', minWidth: 130, gap: spacing.xs, backgroundColor: colors.surfaceMuted, borderRadius: radius.md, padding: spacing.md }, daysRow: { flexDirection: 'row', gap: spacing.xs }, dayItem: { flex: 1, minWidth: 38, alignItems: 'center', gap: spacing.xs, backgroundColor: colors.surfaceMuted, borderRadius: radius.md, paddingVertical: spacing.sm, paddingHorizontal: spacing.xs }, kindRow: { minHeight: 20, flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap' }, noteBox: { backgroundColor: colors.primarySoft, borderRadius: radius.md, padding: spacing.md }, emptyState: { gap: spacing.sm, paddingVertical: spacing.sm } });
