import { Pressable, StyleSheet } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { AppText } from '@/components/AppText';
import { Screen } from '@/components/Screen';
import { Surface } from '@/components/Surface';
import { spacing } from '@/theme/tokens';
const documents={terms:{title:'Termos de Uso',paragraphs:['O BemMeCuida é uma ferramenta de registro, organização e apoio ao autocuidado. Ele não oferece diagnóstico, prescrição, atendimento de emergência ou substituição de profissionais de saúde.','O usuário permanece responsável por procurar atendimento profissional e serviços de emergência quando necessário.','Esta é uma minuta funcional do MVP e deverá passar por revisão jurídica antes da publicação comercial.']},privacy:{title:'Política de Privacidade',paragraphs:['Coletamos apenas os dados necessários para oferecer conta, sincronização, registros e preferências escolhidas pelo usuário.','Dados emocionais e de saúde são tratados como sensíveis, protegidos por controles de acesso e não são vendidos para publicidade.','O usuário poderá solicitar exportação e exclusão de dados em uma etapa posterior do MVP. Esta minuta deverá passar por revisão jurídica.']},'health-data':{title:'Tratamento de dados de saúde',paragraphs:['Check-ins, diário, medicamentos, tratamentos e informações de crise podem revelar aspectos de saúde física ou mental.','Esses dados serão usados somente para as funcionalidades autorizadas, com compartilhamento controlado pelo usuário.','Nenhum conteúdo emocional será enviado a serviços de inteligência artificial sem consentimento específico e uma funcionalidade claramente ativada.']}} as const;
export default function LegalDocumentScreen(){const {document}=useLocalSearchParams<{document:string}>();const content=documents[document as keyof typeof documents]??documents.terms;return <Screen><Pressable onPress={()=>router.back()} accessibilityRole="button"><AppText variant="bodyStrong">← Voltar</AppText></Pressable><AppText variant="h1" style={styles.title}>{content.title}</AppText><Surface style={styles.card}>{content.paragraphs.map((paragraph)=><AppText key={paragraph}>{paragraph}</AppText>)}</Surface><AppText variant="caption" muted style={styles.signature}>Versão MVP · 24 de julho de 2026 · Tehkné Solutions</AppText></Screen>}
const styles=StyleSheet.create({title:{marginVertical:spacing.xl},card:{gap:spacing.lg},signature:{textAlign:'center',marginVertical:spacing.xxl}});
