begin;

alter table public.medications
  add column if not exists stock_tracking_enabled boolean not null default false,
  add column if not exists stock_quantity numeric check (stock_quantity is null or stock_quantity >= 0),
  add column if not exists units_per_intake numeric check (units_per_intake is null or units_per_intake > 0),
  add column if not exists refill_threshold numeric check (refill_threshold is null or refill_threshold >= 0),
  add column if not exists refill_reminder_enabled boolean not null default false,
  add column if not exists refill_reminder_last_sent_at timestamptz;

create table public.professionals (id uuid primary key,user_id uuid not null references auth.users(id) on delete cascade,name text not null check(char_length(name) between 1 and 120),specialty text check(char_length(specialty)<=120),phone text check(char_length(phone)<=40),email text check(char_length(email)<=200),notes text check(char_length(notes)<=400),active boolean not null default true,client_updated_at timestamptz not null,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),deleted_at timestamptz,unique(id,user_id));
create table public.appointments (id uuid primary key,user_id uuid not null references auth.users(id) on delete cascade,professional_id uuid,title text not null check(char_length(title) between 1 and 140),scheduled_at timestamptz not null,duration_minutes smallint check(duration_minutes between 5 and 720),location text check(char_length(location)<=200),notes text check(char_length(notes)<=500),status text not null check(status in ('scheduled','completed','cancelled')),reminder_enabled boolean not null default false,client_updated_at timestamptz not null,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),deleted_at timestamptz,unique(id,user_id),foreign key(professional_id,user_id) references public.professionals(id,user_id) on delete restrict);
create table public.treatments (id uuid primary key,user_id uuid not null references auth.users(id) on delete cascade,professional_id uuid,name text not null check(char_length(name) between 1 and 140),description text check(char_length(description)<=500),start_date date not null,end_date date,status text not null check(status in ('active','paused','completed')),notes text check(char_length(notes)<=500),client_updated_at timestamptz not null,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),deleted_at timestamptz,unique(id,user_id),foreign key(professional_id,user_id) references public.professionals(id,user_id) on delete restrict,check(end_date is null or end_date>=start_date));
create index professionals_user_active_idx on public.professionals(user_id,active,name) where deleted_at is null;
create index appointments_user_scheduled_idx on public.appointments(user_id,scheduled_at desc) where deleted_at is null;
create index treatments_user_status_idx on public.treatments(user_id,status,start_date desc) where deleted_at is null;
create trigger professionals_updated_at before update on public.professionals for each row execute function public.set_updated_at();
create trigger appointments_updated_at before update on public.appointments for each row execute function public.set_updated_at();
create trigger treatments_updated_at before update on public.treatments for each row execute function public.set_updated_at();
alter table public.professionals enable row level security; alter table public.appointments enable row level security; alter table public.treatments enable row level security;
create policy "professionals_select_own" on public.professionals for select to authenticated using ((select auth.uid())=user_id); create policy "professionals_insert_own" on public.professionals for insert to authenticated with check ((select auth.uid())=user_id); create policy "professionals_update_own" on public.professionals for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy "professionals_delete_own" on public.professionals for delete to authenticated using ((select auth.uid())=user_id);
create policy "appointments_select_own" on public.appointments for select to authenticated using ((select auth.uid())=user_id); create policy "appointments_insert_own" on public.appointments for insert to authenticated with check ((select auth.uid())=user_id); create policy "appointments_update_own" on public.appointments for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy "appointments_delete_own" on public.appointments for delete to authenticated using ((select auth.uid())=user_id);
create policy "treatments_select_own" on public.treatments for select to authenticated using ((select auth.uid())=user_id); create policy "treatments_insert_own" on public.treatments for insert to authenticated with check ((select auth.uid())=user_id); create policy "treatments_update_own" on public.treatments for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy "treatments_delete_own" on public.treatments for delete to authenticated using ((select auth.uid())=user_id);

alter function public.sync_care_record(text,jsonb) rename to sync_care_record_v1;
alter function public.pull_care_records(text,timestamptz,uuid,integer) rename to pull_care_records_v1;

create or replace function public.sync_care_record(p_entity_type text,p_record jsonb) returns text language plpgsql security invoker set search_path='' as $$
declare v_user_id uuid:=auth.uid(); v_id uuid:=(p_record->>'id')::uuid; v_client_updated_at timestamptz:=(p_record->>'updatedAt')::timestamptz; v_existing timestamptz;
begin
 if v_user_id is null then raise exception 'authentication_required'; end if; if (p_record->>'userId')::uuid<>v_user_id then raise exception 'account_scope_mismatch'; end if;
 if p_entity_type not in ('medication','professional','appointment','treatment') then return public.sync_care_record_v1(p_entity_type,p_record); end if;
 if p_entity_type='medication' then
  select client_updated_at into v_existing from public.medications where id=v_id and user_id=v_user_id; if v_existing is not null and v_existing>v_client_updated_at then return 'remote_newer'; end if;
  insert into public.medications(id,user_id,name,dosage_text,instructions,prescriber,start_date,end_date,active,stock_tracking_enabled,stock_quantity,units_per_intake,refill_threshold,refill_reminder_enabled,refill_reminder_last_sent_at,client_updated_at,deleted_at)
  values(v_id,v_user_id,p_record->>'name',p_record->>'dosageText',nullif(p_record->>'instructions',''),nullif(p_record->>'prescriber',''),(p_record->>'startDate')::date,case when p_record->>'endDate' is null then null else (p_record->>'endDate')::date end,(p_record->>'active')::boolean,coalesce((p_record->>'stockTrackingEnabled')::boolean,false),case when p_record->>'stockQuantity' is null then null else (p_record->>'stockQuantity')::numeric end,case when p_record->>'unitsPerIntake' is null then null else (p_record->>'unitsPerIntake')::numeric end,case when p_record->>'refillThreshold' is null then null else (p_record->>'refillThreshold')::numeric end,coalesce((p_record->>'refillReminderEnabled')::boolean,false),case when p_record->>'refillReminderLastSentAt' is null then null else (p_record->>'refillReminderLastSentAt')::timestamptz end,v_client_updated_at,case when p_record->>'deletedAt' is null then null else (p_record->>'deletedAt')::timestamptz end)
  on conflict(id) do update set name=excluded.name,dosage_text=excluded.dosage_text,instructions=excluded.instructions,prescriber=excluded.prescriber,start_date=excluded.start_date,end_date=excluded.end_date,active=excluded.active,stock_tracking_enabled=excluded.stock_tracking_enabled,stock_quantity=excluded.stock_quantity,units_per_intake=excluded.units_per_intake,refill_threshold=excluded.refill_threshold,refill_reminder_enabled=excluded.refill_reminder_enabled,refill_reminder_last_sent_at=excluded.refill_reminder_last_sent_at,client_updated_at=excluded.client_updated_at,deleted_at=excluded.deleted_at,updated_at=timezone('utc',now()) where public.medications.user_id=v_user_id and public.medications.client_updated_at<=excluded.client_updated_at;
 elsif p_entity_type='professional' then
  select client_updated_at into v_existing from public.professionals where id=v_id and user_id=v_user_id; if v_existing is not null and v_existing>v_client_updated_at then return 'remote_newer'; end if;
  insert into public.professionals(id,user_id,name,specialty,phone,email,notes,active,client_updated_at,deleted_at) values(v_id,v_user_id,p_record->>'name',nullif(p_record->>'specialty',''),nullif(p_record->>'phone',''),nullif(p_record->>'email',''),nullif(p_record->>'notes',''),(p_record->>'active')::boolean,v_client_updated_at,null) on conflict(id) do update set name=excluded.name,specialty=excluded.specialty,phone=excluded.phone,email=excluded.email,notes=excluded.notes,active=excluded.active,client_updated_at=excluded.client_updated_at,deleted_at=excluded.deleted_at,updated_at=timezone('utc',now()) where public.professionals.user_id=v_user_id and public.professionals.client_updated_at<=excluded.client_updated_at;
 elsif p_entity_type='appointment' then
  select client_updated_at into v_existing from public.appointments where id=v_id and user_id=v_user_id; if v_existing is not null and v_existing>v_client_updated_at then return 'remote_newer'; end if;
  insert into public.appointments(id,user_id,professional_id,title,scheduled_at,duration_minutes,location,notes,status,reminder_enabled,client_updated_at,deleted_at) values(v_id,v_user_id,case when p_record->>'professionalId' is null then null else (p_record->>'professionalId')::uuid end,p_record->>'title',(p_record->>'scheduledAt')::timestamptz,case when p_record->>'durationMinutes' is null then null else (p_record->>'durationMinutes')::smallint end,nullif(p_record->>'location',''),nullif(p_record->>'notes',''),p_record->>'status',(p_record->>'reminderEnabled')::boolean,v_client_updated_at,null) on conflict(id) do update set professional_id=excluded.professional_id,title=excluded.title,scheduled_at=excluded.scheduled_at,duration_minutes=excluded.duration_minutes,location=excluded.location,notes=excluded.notes,status=excluded.status,reminder_enabled=excluded.reminder_enabled,client_updated_at=excluded.client_updated_at,deleted_at=excluded.deleted_at,updated_at=timezone('utc',now()) where public.appointments.user_id=v_user_id and public.appointments.client_updated_at<=excluded.client_updated_at;
 else
  select client_updated_at into v_existing from public.treatments where id=v_id and user_id=v_user_id; if v_existing is not null and v_existing>v_client_updated_at then return 'remote_newer'; end if;
  insert into public.treatments(id,user_id,professional_id,name,description,start_date,end_date,status,notes,client_updated_at,deleted_at) values(v_id,v_user_id,case when p_record->>'professionalId' is null then null else (p_record->>'professionalId')::uuid end,p_record->>'name',nullif(p_record->>'description',''),(p_record->>'startDate')::date,case when p_record->>'endDate' is null then null else (p_record->>'endDate')::date end,p_record->>'status',nullif(p_record->>'notes',''),v_client_updated_at,null) on conflict(id) do update set professional_id=excluded.professional_id,name=excluded.name,description=excluded.description,start_date=excluded.start_date,end_date=excluded.end_date,status=excluded.status,notes=excluded.notes,client_updated_at=excluded.client_updated_at,deleted_at=excluded.deleted_at,updated_at=timezone('utc',now()) where public.treatments.user_id=v_user_id and public.treatments.client_updated_at<=excluded.client_updated_at;
 end if; return 'applied';
end; $$;

create or replace function public.pull_care_records(p_entity_type text,p_cursor_updated_at timestamptz default '1970-01-01 00:00:00+00',p_cursor_id uuid default '00000000-0000-0000-0000-000000000000',p_limit integer default 500) returns table(entity_type text,entity_id uuid,server_updated_at timestamptz,payload jsonb) language plpgsql stable security invoker set search_path='' as $$
begin
 if p_entity_type not in ('professional','appointment','treatment') then return query select * from public.pull_care_records_v1(p_entity_type,p_cursor_updated_at,p_cursor_id,p_limit);
 elsif p_entity_type='professional' then return query select p_entity_type,item.id,item.updated_at,to_jsonb(item) from public.professionals item where item.user_id=auth.uid() and (item.updated_at>p_cursor_updated_at or (item.updated_at=p_cursor_updated_at and item.id>p_cursor_id)) order by item.updated_at,item.id limit least(greatest(coalesce(p_limit,500),1),500);
 elsif p_entity_type='appointment' then return query select p_entity_type,item.id,item.updated_at,to_jsonb(item) from public.appointments item where item.user_id=auth.uid() and (item.updated_at>p_cursor_updated_at or (item.updated_at=p_cursor_updated_at and item.id>p_cursor_id)) order by item.updated_at,item.id limit least(greatest(coalesce(p_limit,500),1),500);
 else return query select p_entity_type,item.id,item.updated_at,to_jsonb(item) from public.treatments item where item.user_id=auth.uid() and (item.updated_at>p_cursor_updated_at or (item.updated_at=p_cursor_updated_at and item.id>p_cursor_id)) order by item.updated_at,item.id limit least(greatest(coalesce(p_limit,500),1),500); end if;
end; $$;
revoke all on function public.sync_care_record(text,jsonb) from public; grant execute on function public.sync_care_record(text,jsonb) to authenticated;
revoke all on function public.pull_care_records(text,timestamptz,uuid,integer) from public; grant execute on function public.pull_care_records(text,timestamptz,uuid,integer) to authenticated;
commit;
